#encoding: utf-8

DEBUG = True

DIALECT = 'mysql'
DRIVER = 'mysqldb'
USERNAME = '102Xi102'
PASSWORD = 'X123456i'
HOST = '139.224.54.233'
PORT = '3306'
DATABASE = 'UMLS'
SECRET_KEY='12345678'

SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT, DRIVER, USERNAME, PASSWORD, HOST , PORT, DATABASE)

SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_ON_TEARDOWN = True